### ISSUE TITLE
Add methods related to invoices

### ISSUE THREAD

**Issue by karan-dreambits** [dreambits/python-bol-api#10]
The following methods related to invoices are available in the bol api but not yet implemented in the current version of this library.

The following are stable and needed:

- Invoice list : https://developers.bol.com/invoice-list/

- Get single invoice : https://developers.bol.com/invoice-single/

There are certain Invoice line types that might be needed to be supported in models.py before the above methods can be implemented.

The list of invoice line types can be found here : https://developers.bol.com/invoice-line-types/

**Comment by jasonbrookins** [comment]
I have some experience creating and implementing an invoice system, so would you mind if I took a look at this?

**Comment by karan-dreambits** [comment]
@jasonbrookins sure, have you used Bol.com or aware about it ?

**Comment by jasonbrookins** [comment]
I'm getting slammed at work right now, so I won't really have much time in the near future to hit this.  If it stays open, I can try it when I don't have as much demand on my time.
