### ISSUE TITLE
Api fails when working with test credentials and test mode.

### ISSUE THREAD

**Issue by karan-dreambits** [dreambits/python-bol-api#20]
It seems that we new api v2,
Test mode is not completely ported.

Fetching orders fails as no proper response is coming from bol

It seems that the accept param

> application/vnd.orders-v2.1+xml

is causing issue

**Comment by devang-dreambits** [comment]
API test environment is currently not available and it will be removed in the future version.

An official statement relevant to this can be found at https://developers.bol.com/api-test-facility/
